#define ETH_STATUS 0
#define ETH_SEND 1
#define ETH_RCVACK 2
#define ETH_SOFTRST 4
#define ETH_DUMMY 5
#define ETH_TX_NBYTES 6
#define ETH_RX_NBYTES 7
#define ETH_CRC 8
#define ETH_RCV_SIZE 9
#define ETH_DATA 2048
