# SPDX-FileCopyrightText: 2025 IObundle
#
# SPDX-License-Identifier: MIT

import os


def gen_custom_config_build(py_params_dict):
    content = """
#This file was auto generated by gen_custom_config_build.py

### Set Ethernet environment variables
#Eth interface address of pc connected to ethernet peripheral (based on board name)
$(if $(findstring sim,$(MAKECMDGOALS))$(SIMULATOR),$(eval BOARD=))
ifeq ($(BOARD),iob_aes_ku040_db_g)
ETH_IF ?=eno1
endif
ifeq ($(BOARD),iob_cyclonev_gt_dk)
ETH_IF ?= enp0s31f6
endif
# Set a MAC address for console (randomly generated)
RMAC_ADDR ?=88431eafa897
export RMAC_ADDR
#Set correct environment if running on IObundle machines
ifneq ($(filter feynman pudim-flan sericaia,$(shell hostname)),)
IOB_CONSOLE_PYTHON_ENV ?= /opt/pyeth3/bin/python
else
IOB_CONSOLE_PYTHON_ENV ?= $(ROOT_DIR)/scripts/pyRawWrapper/pyRawWrapper
endif
"""

    if (
        py_params_dict.get("py2hwsw_target", "") == "setup"
        and py_params_dict["build_dir"]
    ):
        os.makedirs(py_params_dict["build_dir"], exist_ok=True)
        file_path = os.path.join(py_params_dict["build_dir"], "custom_config_build.mk")
        with open(file_path, "w") as f:
            f.write(content)
            f.close()
