# SPDX-FileCopyrightText: 2025 IObundle
#
# SPDX-License-Identifier: MIT

name: Release-Artifacts

on:
  release:
    types: [created, edited, prereleased, published, released]
  # Allow manual workflow runs
  workflow_dispatch:

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}


# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-release-artifacts:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: Build release artifacts
        run: make release-artifacts
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
